all:
  children:
    alma_cluster:
      children:
        controller:
          hosts:
            controller1:
              ansible_host: 192.168.0.244
              ansible_user: '{{ admin_user }}'
              ansible_ssh_private_key_file: '{{ cluster_ssh_key }}'
            controller2:
              ansible_host: 192.168.0.107
              ansible_user: '{{ admin_user }}'
              ansible_ssh_private_key_file: '{{ cluster_ssh_key }}'
        worker:
          hosts:
            worker1:
              ansible_host: 192.168.0.116
              ansible_user: '{{ admin_user }}'
              ansible_ssh_private_key_file: '{{ cluster_ssh_key }}'
            worker2:
              ansible_host: 192.168.0.160
              ansible_user: '{{ admin_user }}'
              ansible_ssh_private_key_file: '{{ cluster_ssh_key }}'
