---
all:
  children:
    alma_cluster:
      children:
        controller:
          hosts:
            controller1:
              ansible_host: 192.168.0.240
              ansible_user: "{{ admin_user }}"
              ansible_password: "{{ cluster_password }}"
            controller2:
              ansible_host: 192.168.0.42
              ansible_user: "{{ admin_user }}"
              ansible_password: "{{ cluster_password }}"
        worker:
          hosts:
            worker1:
              ansible_host: 192.168.0.86
              ansible_user: "{{ admin_user }}"
              #ansible_ssh_private_key_file: /path/file
              ansible_password: "{{ cluster_password }}"
            worker2:
              ansible_host: 192.168.0.22
              ansible_user: "{{ admin_user }}"
              #ansible_ssh_private_key_file: /path/file
              ansible_password: "{{ cluster_password }}"