all:
  children:
    alma_cluster:
      children:
        controller:
          hosts:
            controller1:
              ansible_host: 192.168.0.173
              ansible_user: '{{ admin_user }}'
              ansible_password: '{{ cluster_password }}'
            controller2:
              ansible_host: 192.168.0.11
              ansible_user: '{{ admin_user }}'
              ansible_password: '{{ cluster_password }}'
        worker:
          hosts:
            worker1:
              ansible_host: 192.168.0.182
              ansible_user: '{{ admin_user }}'
              ansible_password: '{{ cluster_password }}'
            worker2:
              ansible_host: 192.168.0.146
              ansible_user: '{{ admin_user }}'
              ansible_password: '{{ cluster_password }}'
