---
all:
  children:
    alma_cluster:
      children:
        controller:
          hosts:
            controller1:
              ansible_host: 192.168.0.124
              ansible_user: "{{ admin_user }}"
              ansible_password: "{{ cluster_password }}"
            # controller2:
            #   ansible_host: 192.168.0.88
            #   ansible_user: "{{ admin_user }}"
            #   ansible_password: "{{ cluster_password }}"
        worker:
          hosts:
            worker1:
              ansible_host: 192.168.0.195
              ansible_user: "{{ admin_user }}"
              #ansible_ssh_private_key_file: /path/file
              ansible_password: "{{ cluster_password }}"
            worker2:
              ansible_host: 192.168.0.120
              ansible_user: "{{ admin_user }}"
              #ansible_ssh_private_key_file: /path/file
              ansible_password: "{{ cluster_password }}"