all:
  children:
    alma_cluster:
      children:
        controller:
          hosts:
            controller1:
              ansible_host: 192.168.0.147
              ansible_user: '{{ admin_user }}'
              ansible_password: '{{ cluster_password }}'
            controller2:
              ansible_host: 192.168.0.204
              ansible_user: '{{ admin_user }}'
              ansible_password: '{{ cluster_password }}'
        worker:
          hosts:
            worker1:
              ansible_host: 192.168.0.206
              ansible_user: '{{ admin_user }}'
              ansible_password: '{{ cluster_password }}'
            worker2:
              ansible_host: 192.168.0.20
              ansible_user: '{{ admin_user }}'
              ansible_password: '{{ cluster_password }}'
