---
- hosts: alma_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq

- hosts: controller
  become: true
  roles:
    - role: k8s/controller

- name: Adding workers
  hosts: worker
  become: true
  roles:
    - role: k8s/worker

- hosts: localhost
  become: true
  roles:
    - role: k8s/cluster

- name: Extra controllers
  hosts: controller
  tasks:
  - include_tasks: ansible/roles/k8s/controller/tasks/extra_controllers.yml
