---
# - name: Enable control plane
#   become: true
#   ansible.builtin.shell: kubeadm init --control-plane-endpoint={{ inventory_hostname }}.{ {domain }}

- name: Enable TCP firewall for worker
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 30000-32767/tcp
    - 10250/tcp
    - 179/tcp
  notify: Reload firewall

- name: Enable UDP firewall for worker
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 4789/udp
  notify: Reload firewall

- name: Join worker nodes to the cluster
  command: "sudo kubeadm join --token {{ hostvars[groups['controller'][0]]['join_token'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['controller'][0]]['sha_hash'] }}"