---
# - name: Enable control plane
#   become: true
#   ansible.builtin.shell: kubeadm init --control-plane-endpoint={{ inventory_hostname }}.{ {domain }}

- name: Enable TCP firewall for worker
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 30000-32767/tcp
    - 10250/tcp
    - 179/tcp
  notify: Reload firewall

- name: Enable UDP firewall for worker
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 4789/udp
  notify: Reload firewall

- name: Check if the worker has been initialized
  stat:
    path: "{{ ansible_env.HOME }}/worker_initialized"
  register: worker_initialized_file

- name: Join worker nodes to the cluster
  command: "{{ hostvars[groups['controller'][0]]['join_command'] }}"
  when: worker_initialized_file.stat.exists is not defined or worker_initialized_file.stat.exists == false

- name: Create initialized flag file for workers
  file:
    path: "{{ ansible_env.HOME }}/worker_initialized"
    state: touch
  when: worker_initialized_file.stat.exists is not defined or worker_initialized_file.stat.exists == false
